// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkhvditcyloxshxakwao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtraHZkaXRjeWxveHNoeGFrd2FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzcyNTEsImV4cCI6MjA2ODE1MzI1MX0.oIGK8fn7Y9hePSyiZiutY-62_mHXcnuu26HB3DmxRnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});